Terminating on signal 15
Terminating on signal 15
Traceback (most recent call last):
  File "/home/sean/deploy/LAMSON/bin/lamson", line 5, in <module>
    pkg_resources.run_script('lamson==1.0pre6', 'lamson')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 448, in run_script
Traceback (most recent call last):
  File "/home/sean/deploy/LAMSON/bin/lamson", line 5, in <module>
    pkg_resources.run_script('lamson==1.0pre6', 'lamson')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 448, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1166, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1166, in run_script
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/EGG-INFO/scripts/lamson", line 6, in <module>
    args.parse_and_run_command(sys.argv[1:], commands, default_command="help")
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/args.py", line 304, in parse_and_run_command
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/EGG-INFO/scripts/lamson", line 6, in <module>
        args.parse_and_run_command(sys.argv[1:], commands, default_command="help")
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/args.py", line 304, in parse_and_run_command
    command_module(mod, command, options)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/args.py", line 230, in command_module
    return function(**options)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/commands.py", line 62, in log_command
    utils.start_server(pid, FORCE, chroot, chdir, uid, gid, umask, loader)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/utils.py", line 99, in start_server
command_module(mod, command, options)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/args.py", line 230, in command_module
    return function(**options)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/commands.py", line 111, in start_command
    utils.start_server(pid, FORCE, chroot, chdir, uid, gid, umask, loader)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/utils.py", line 99, in start_server
    daemonize(pid, chdir, chroot, umask, files_preserve=[])
    daemonize(pid, chdir, chroot, umask, files_preserve=[])
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/utils.py", line 49, in daemonize
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/utils.py", line 49, in daemonize
    context.open()
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/python_daemon-1.5.2-py2.6.egg/daemon/daemon.py", line 344, in open
    context.open()
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/python_daemon-1.5.2-py2.6.egg/daemon/daemon.py", line 344, in open
    self.pidfile.__enter__()
  File "build/bdist.linux-i686/egg/lockfile.py", line 223, in __enter__
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/python_daemon-1.5.2-py2.6.egg/daemon/pidlockfile.py", line 59, in acquire
    self.pidfile.__enter__()
  File "build/bdist.linux-i686/egg/lockfile.py", line 223, in __enter__
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/python_daemon-1.5.2-py2.6.egg/daemon/pidlockfile.py", line 59, in acquire
    super(PIDLockFile, self).acquire(*args, **kwargs)
  File "build/bdist.linux-i686/egg/lockfile.py", line 251, in acquire
OSError: [Errno 2] No such file or directory: '/home/sean/deploy/postosaurus/run/zeus.MainThread-10065'
    super(PIDLockFile, self).acquire(*args, **kwargs)
  File "build/bdist.linux-i686/egg/lockfile.py", line 251, in acquire
OSError: [Errno 2] No such file or directory: '/home/sean/deploy/postosaurus/run/zeus.MainThread-10068'
Terminating on signal 15
Traceback (most recent call last):
  File "/home/sean/deploy/LAMSON/bin/lamson", line 5, in <module>
    pkg_resources.run_script('lamson==1.0pre6', 'lamson')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 448, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1166, in run_script
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/EGG-INFO/scripts/lamson", line 6, in <module>
    args.parse_and_run_command(sys.argv[1:], commands, default_command="help")
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/args.py", line 304, in parse_and_run_command
    command_module(mod, command, options)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/args.py", line 230, in command_module
    return function(**options)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/commands.py", line 111, in start_command
    utils.start_server(pid, FORCE, chroot, chdir, uid, gid, umask, loader)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/utils.py", line 99, in start_server
    daemonize(pid, chdir, chroot, umask, files_preserve=[])
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/utils.py", line 49, in daemonize
    context.open()
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/python_daemon-1.5.2-py2.6.egg/daemon/daemon.py", line 344, in open
    self.pidfile.__enter__()
  File "build/bdist.linux-i686/egg/lockfile.py", line 223, in __enter__
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/python_daemon-1.5.2-py2.6.egg/daemon/pidlockfile.py", line 59, in acquire
    super(PIDLockFile, self).acquire(*args, **kwargs)
  File "build/bdist.linux-i686/egg/lockfile.py", line 251, in acquire
OSError: [Errno 2] No such file or directory: '/home/sean/deploy/postosaurus/run/zeus.MainThread-19487'
Traceback (most recent call last):
  File "/home/sean/deploy/LAMSON/bin/lamson", line 5, in <module>
    pkg_resources.run_script('lamson==1.0pre6', 'lamson')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 448, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1166, in run_script
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/EGG-INFO/scripts/lamson", line 6, in <module>
    args.parse_and_run_command(sys.argv[1:], commands, default_command="help")
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/args.py", line 304, in parse_and_run_command
    command_module(mod, command, options)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/args.py", line 230, in command_module
    return function(**options)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/commands.py", line 111, in start_command
    utils.start_server(pid, FORCE, chroot, chdir, uid, gid, umask, loader)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/utils.py", line 103, in start_server
    settings = settings_loader()
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/commands.py", line 110, in <lambda>
    loader = lambda: utils.import_settings(True, from_dir=os.getcwd(), boot_module=boot)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/utils.py", line 21, in import_settings
    settings = __import__("config.settings", globals(), locals()).settings
  File "/home/sean/deploy/postosaurus/config/settings.py", line 4, in <module>
    os.environ['DJANGO_SETTINGS_MODULE'] = 'webapp.settings'
NameError: name 'os' is not defined
Traceback (most recent call last):
  File "/home/sean/deploy/LAMSON/bin/lamson", line 5, in <module>
    pkg_resources.run_script('lamson==1.0pre6', 'lamson')
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 448, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1166, in run_script
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/EGG-INFO/scripts/lamson", line 6, in <module>
    args.parse_and_run_command(sys.argv[1:], commands, default_command="help")
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/args.py", line 304, in parse_and_run_command
    command_module(mod, command, options)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/args.py", line 230, in command_module
    return function(**options)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/commands.py", line 111, in start_command
    utils.start_server(pid, FORCE, chroot, chdir, uid, gid, umask, loader)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/utils.py", line 103, in start_server
    settings = settings_loader()
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/commands.py", line 110, in <lambda>
    loader = lambda: utils.import_settings(True, from_dir=os.getcwd(), boot_module=boot)
  File "/home/sean/deploy/LAMSON/lib/python2.6/site-packages/lamson-1.0pre6-py2.6.egg/lamson/utils.py", line 21, in import_settings
    settings = __import__("config.settings", globals(), locals()).settings
  File "/home/sean/deploy/postosaurus/config/settings.py", line 4, in <module>
    os.environ['DJANGO_SETTINGS_MODULE'] = 'webapp.settings'
NameError: name 'os' is not defined
